server {
    listen 8080;
    server_name localhost;

    location /api {
        proxy_pass https://lstalk-api-morning-sky-4784.fly.dev/api;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host lstalk-api-morning-sky-4784.fly.dev;
        proxy_cache_bypass $http_upgrade;
        proxy_ssl_server_name on;
    }

    location /socket.io {
        proxy_pass https://lstalk-api-morning-sky-4784.fly.dev/socket.io;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host lstalk-api-morning-sky-4784.fly.dev;
        proxy_ssl_server_name on;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Optional: Handle static assets with long caching
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|otf)$ {
        root /usr/share/nginx/html;
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
